# Generated by Django 5.2.6 on 2025-09-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishingredient',
            name='amount_required',
            field=models.DecimalField(decimal_places=2, help_text='Ilość składnika potrzebna na 1 porcję', max_digits=8),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='stock_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current stock', max_digits=6),
        ),
        migrations.AlterField(
            model_name='ingredienttransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
