# Generated by Django 5.2.6 on 2025-09-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_ingredient_order_cook_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
