# Generated by Django 5.2.6 on 2025-09-26 08:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_alter_cook_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default='kg', help_text='Unit e.g., kg, l, pcs', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='stock_amount',
            field=models.FloatField(default=0, help_text='Current stock'),
        ),
        migrations.CreateModel(
            name='IngredientTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('SUPPLY', 'Supply'), ('WASTE', 'Waste'), ('EDIT', 'Edit Stock')], max_length=10)),
                ('quantity', models.FloatField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateField(blank=True, help_text='Required for SUPPLY', null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='kitchen.ingredient')),
            ],
        ),
    ]
