# Generated by Django 5.2.6 on 2025-09-26 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_remove_ingredient_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredienttransaction',
            name='source_supply',
            field=models.ForeignKey(blank=True, limit_choices_to={'transaction_type': 'SUPPLY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wasted_from', to='kitchen.ingredienttransaction'),
        ),
        migrations.AlterField(
            model_name='ingredienttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('SUPPLY', 'Supply'), ('WASTE', 'Waste')], max_length=10),
        ),
    ]
