# Generated by Django 5.2.6 on 2025-09-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_ingredienttransaction_source_supply_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredienttransaction',
            name='source_supply',
        ),
        migrations.AddField(
            model_name='ingredienttransaction',
            name='source_transactions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'transaction_type': 'SUPPLY'}, related_name='waste_used_in', to='kitchen.ingredienttransaction'),
        ),
        migrations.AlterField(
            model_name='ingredienttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('SUPPLY', 'Supply'), ('WASTE', 'Waste'), ('EDIT', 'Edit Stock')], max_length=10),
        ),
    ]
