# Generated by Django 5.2.6 on 2025-09-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0006_remove_ingredienttransaction_source_supply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('SUPPLY', 'Supply'), ('WASTE', 'Waste')], max_length=10),
        ),
    ]
